spring.datasource.url=jdbc:mysql://localhost:3306/billingSoftware
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0

aws.access.key=AKIAXD7VOYEK4VW6Y2GI
aws.secret.key=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
aws.region=ap-south-1
aws.bucket.name=billing-software-application-sambhav

jwt.secret.key=9f8e7d6c5b4a3928172635448392afed9f8e7d6c5b4a3928172635448392afed
